### ISSUE TITLE
filters in code not consistent with it in paper

### ISSUE THREAD

**Issue by huosan0123** [nh2tran/DeepNovo#2]
I'm interested in your nice work. But I have confusion about it. In spectrum-CNN part in SI Text of your paper, It seems that the filter's size in paper(2*10) not consistent with that in your code(# conv1: filter [1, 4, 1, 4] with stride [1, 1, 1, 1]).

**Comment by nh2tran** [comment]
Thanks for your interest. The version of spectrum-CNN model described in
the paper has been deprecated, at least for now, because we found it hard
to train it together with other models in an end-to-end fashion. Currently
we use a simpler version and we are still studying how to improve it.

Hope this helps, and thanks again for your interest in our work!

**Comment by huosan0123** [comment]
May I ask: what does "beam search" mean and it works which part of your model? 
Another question is:  I don't know what does "SCANS=F1:799" do, I am not familiar with this item in dataset.
